### ISSUE TITLE
unable to send file to AS2 server from AS2-LIB

### ISSUE THREAD

**Issue by ankitagrawa** [phax/as2-lib#126]
1) What does "MIC IS NOT MATCHED" mean?

 INFO  com.helger.as2lib.processor.sender.AS2SenderModule  - MIC IS NOT MATCHED, original mic: '8EU1L2J0xEcy1F/2st3s0rqWqFHlMOqtU91xAnWzn8U=, sha256' return mic: 'null' [<17092021162016+0000-1627@xyz>] [
source:xyr]
                                                                                                                                                                                      
2) What does "Invalid disposition type format: null" mean? What is disposition type?
 INFO  com.helger.as2lib.exception.OpenAS2Exception  - OpenAS2 OpenAS2Exception terminated: Message was sent but an error occured while receiving the MDN                                                                                                                                                
com.helger.as2lib.exception.OpenAS2Exception: Invalid disposition type format: null                                                                                                                               
        at com.helger.as2lib.disposition.DispositionType.createFromString(DispositionType.java:175)                                                                                                               
        at com.helger.as2lib.processor.sender.AS2SenderModule.receiveSyncMDN(AS2SenderModule.java:707)                                                                                                            
        at com.helger.as2lib.processor.sender.AS2SenderModule._sendViaHTTP(AS2SenderModule.java:867)                                                                                                              
        at com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:932)       
        
Is there a workaround for this?

**Comment by phax** [comment]
The source problem is the message `Invalid disposition type format: null`

**Comment by phax** [comment]
(sorry, clicked by accident)

**Comment by ankitagrawa** [comment]
@phax  : What does that mean?? Does it mean the other server didn't send a correct response?

**Comment by phax** [comment]
Does the edited answer from above answer your question?

**Comment by ankitagrawa** [comment]
I guess yes. Need to check few things from the receiver.
