### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by phax** [phax/as2-lib#33]
```
[2018-03-05T19:40:42,459] [ERB] [INFO ] [ajp-nio-127.0.0.1-8009-exec-21] OpenAS2 WrappedOpenAS2Exception terminated: java.lang.NullPointerException: The value of 'MimeBodyPart' may not be null!; sources: {message=[AS2Message@0x1e28fd3b: data=null; MDN=[[AS2MessageMDN@0x63825fb4: attributes=[{REPORTING_UA=ph-OpenAS2 4.0.0@172.18.112.1:443, ORIGINAL_RECIPIENT=rfc822; APP_1000000135, FINAL_RECIPIENT=rfc822; null, ORIGINAL_MESSAGE_ID=<EIZMU89AT3U4.0M6F7Q1U6K1X1@NikolayPC>, DISPOSITION=automatic-action/MDN-sent-automatically; processed/Error:unexpected-processing-error}]; headers=[HttpHeaderMap@0x27aafcdb: Headers={as2-to=[APP_1000000345], as2-from=[APP_1000000135], as2-version=[1.1], date=[Mo, 05 M?r 2018 20:40:42 +0100], server=[ph-OpenAS2 4.0.0], mime-version=[1.0], subject=[Your Requested MDN Response]}]; partnership=[Partnership@0x71f6a35c: name=APP_1000000135-APP_1000000345; senderIDs=[{as2_id=APP_1000000135, x509_alias=null}]; receiverIDs=[{as2_id=APP_1000000345, x509_alias=null}]; attributes=[{sign=sha-1}]]]; message=<EIZMU89AT3U4.0M6F7Q1U6K1X1@NikolayPC>; data=null; text=The message sent to Recipient null on Mon, 05 Mar 2018 19:40:39 GMT with Subject AS2 message from Databutikken Access Point has been received, but an error occured while parsing the MIME content.]]} -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:108)
java.lang.NullPointerException: The value of 'MimeBodyPart' may not be null!
	at com.helger.commons.ValueEnforcer.notNull(ValueEnforcer.java:276) ~[ph-commons-9.0.1.jar:9.0.1]
	at com.helger.as2lib.crypto.BCCryptoHelper.calculateMIC(BCCryptoHelper.java:256) ~[as2-lib-4.0.0.jar:4.0.0]
	at com.helger.as2lib.util.AS2Helper.createMDN(AS2Helper.java:304) ~[as2-lib-4.0.0.jar:4.0.0]
	at com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.sendSyncMDN(AS2ReceiverHandler.java:270) [as2-lib-4.0.0.jar:4.0.0]
	at com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handleIncomingMessage(AS2ReceiverHandler.java:536) [as2-lib-4.0.0.jar:4.0.0]
	at com.helger.as2servlet.AbstractAS2ReceiveXServletHandler.handeIncomingMessage(AbstractAS2ReceiveXServletHandler.java:162) [as2-servlet-4.0.0.jar:4.0.0]
	at at.gv.brz.erb.webapp.servlet.ERBAS2ReceiveXServletHandler.handeIncomingMessage(ERBAS2ReceiveXServletHandler.java:81) [classes/:5.0.6]
	at com.helger.as2servlet.AbstractAS2ReceiveXServletHandler.onRequest(AbstractAS2ReceiveXServletHandler.java:198) [as2-servlet-4.0.0.jar:4.0.0]
	at com.helger.xservlet.AbstractXServlet._invokeHandler(AbstractXServlet.java:336) [ph-xservlet-9.0.0.jar:9.0.0]
	at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:520) [ph-xservlet-9.0.0.jar:9.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.46]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.46]
	at com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:183) [ph-servlet-9.0.0.jar:9.0.0]
	at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.0.0.jar:9.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.46]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.10.0.jar:2.10.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.46]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.46]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94) [catalina.jar:8.0.46]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.46]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.46]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:8.0.46]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.46]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502) [catalina.jar:8.0.46]
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:877) [tomcat-coyote.jar:8.0.46]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684) [tomcat-coyote.jar:8.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539) [tomcat-coyote.jar:8.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495) [tomcat-coyote.jar:8.0.46]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.46]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[2018-03-05T19:40:42,470] [ERB] [INFO ] [ajp-nio-127.0.0.1-8009-exec-21] OpenAS2 DispositionException terminated: automatic-action/MDN-sent-automatically; processed/Error:unexpected-processing-error; sources: {message=[AS2Message@0x1e28fd3b: data=null; MDN=[[AS2MessageMDN@0x63825fb4: attributes=[{REPORTING_UA=ph-OpenAS2 4.0.0@172.18.112.1:443, ORIGINAL_RECIPIENT=rfc822; APP_1000000135, FINAL_RECIPIENT=rfc822; null, ORIGINAL_MESSAGE_ID=<EIZMU89AT3U4.0M6F7Q1U6K1X1@NikolayPC>, DISPOSITION=automatic-action/MDN-sent-automatically; processed/Error:unexpected-processing-error}]; headers=[HttpHeaderMap@0x27aafcdb: Headers={as2-to=[APP_1000000345], as2-from=[APP_1000000135], as2-version=[1.1], date=[Mo, 05 M?r 2018 20:40:42 +0100], server=[ph-OpenAS2 4.0.0], mime-version=[1.0], subject=[Your Requested MDN Response]}]; partnership=[Partnership@0x71f6a35c: name=APP_1000000135-APP_1000000345; senderIDs=[{as2_id=APP_1000000135, x509_alias=null}]; receiverIDs=[{as2_id=APP_1000000345, x509_alias=null}]; attributes=[{sign=sha-1}]]]; message=<EIZMU89AT3U4.0M6F7Q1U6K1X1@NikolayPC>; data=null; text=The message sent to Recipient null on Mon, 05 Mar 2018 19:40:39 GMT with Subject AS2 message from Databutikken Access Point has been received, but an error occured while parsing the MIME content.]]} -- com.helger.as2lib.exception.OpenAS2Exception.log(OpenAS2Exception.java:108)
javax.mail.internet.ParseException: In Content-Type string <null>, expected MIME type, got null
	at javax.mail.internet.ContentType.<init>(ContentType.java:97) ~[javax.mail-1.6.0.jar:1.6.0]
	at com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler.handleIncomingMessage(AS2ReceiverHandler.java:362) [as2-lib-4.0.0.jar:4.0.0]
	at com.helger.as2servlet.AbstractAS2ReceiveXServletHandler.handeIncomingMessage(AbstractAS2ReceiveXServletHandler.java:162) [as2-servlet-4.0.0.jar:4.0.0]
	at at.gv.brz.erb.webapp.servlet.ERBAS2ReceiveXServletHandler.handeIncomingMessage(ERBAS2ReceiveXServletHandler.java:81) [classes/:5.0.6]
	at com.helger.as2servlet.AbstractAS2ReceiveXServletHandler.onRequest(AbstractAS2ReceiveXServletHandler.java:198) [as2-servlet-4.0.0.jar:4.0.0]
	at com.helger.xservlet.AbstractXServlet._invokeHandler(AbstractXServlet.java:336) [ph-xservlet-9.0.0.jar:9.0.0]
	at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:520) [ph-xservlet-9.0.0.jar:9.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.46]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.46]
	at com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:183) [ph-servlet-9.0.0.jar:9.0.0]
	at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.0.0.jar:9.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.46]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.10.0.jar:2.10.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.46]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.46]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94) [catalina.jar:8.0.46]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.46]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.46]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:8.0.46]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.46]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502) [catalina.jar:8.0.46]
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:877) [tomcat-coyote.jar:8.0.46]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684) [tomcat-coyote.jar:8.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539) [tomcat-coyote.jar:8.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495) [tomcat-coyote.jar:8.0.46]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.46]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by phax** [comment]
`new ContentType (String)` is now centrally encapsulated
