### ISSUE TITLE
Exception in client when sending a message clear text messagse

### ISSUE THREAD

**Issue by zharpaz** [phax/as2-lib#45]
Hi Philip,
When sending a message with no encryption, signature, or compression, the call
aSecuredMimePart.getInputStream() (AS2SenderModule:682) fails with Exception javax.activation.UnsupportedDataTypeException: no object DCH for MIME type application/xml.
Thanks,  Ziv

**Comment by phax** [comment]
I tried to reproduce that but failed. I was sending an unsigned, unencrypted, non-compressed messages without an issue. Do you have any additional libraries in your `jre/ext` folder?

**Comment by zharpaz** [comment]
It works OK when the data is set with 
`aRequest.setData ("toSend", Charset.defaultCharset());`
if fails with
`aRequest.setData (new File("file.txt"));`

**Comment by phax** [comment]
I see. When no `Charset` is provided, the following exception occurs:
```
1342 [main] INFO com.helger.as2lib.exception.OpenAS2Exception - OpenAS2 WrappedOpenAS2Exception terminated: java.io.IOException: "text/plain" DataContentHandler requires String object, was given object of type class [B; sources: {message=[AS2Message@0x2630dbc4: data=javax.mail.internet.MimeBodyPart@5ea4300e; MDN=null]}
java.io.IOException: "text/plain" DataContentHandler requires String object, was given object of type class [B
	at com.sun.mail.handlers.text_plain.writeTo(text_plain.java:133)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at com.helger.as2lib.crypto.BCCryptoHelper.calculateMIC(BCCryptoHelper.java:321)
	at com.helger.as2lib.processor.sender.AS2SenderModule.calculateAndStoreMIC(AS2SenderModule.java:272)
	at com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:815)
	at com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:402)
	at com.helger.as2lib.supplementary.main.MainIssue45.main(MainIssue45.java:116)
```
When instead calling
```
aRequest.setData (new File ("file.txt"), Charset.defaultCharset ());
```
it works for me.
