### ISSUE TITLE
MainSendToMendelsonTestServer - Can'r run this test (4.2.0-RC1)

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#62]
Hi Philip,
You changes the algorithm to:
    final ECryptoAlgorithmSign eSignAlgo = ECryptoAlgorithmSign.DIGEST_SHA_512;
    final ECryptoAlgorithmCrypt eCryptAlgo = ECryptoAlgorithmCrypt.CRYPT_AES256_CBC;
When I run this class I am getting:

2543 [main] INFO com.helger.as2lib.processor.sender.AS2SenderModule - Submitting message [<github-phax-as2-lib-30082018180454+0300-4815@mycompanyAS2_mendelsontestAS2>]
7528 [main] ERROR com.helger.as2lib.client.AS2Client - Error sending AS2 message
com.helger.as2lib.exception.WrappedOpenAS2Exception: org.bouncycastle.cms.CMSException: unable to initialize cipher: Illegal key size
	at com.helger.as2lib.exception.WrappedOpenAS2Exception.wrap(WrappedOpenAS2Exception.java:66)
	at com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:879)
	at com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:402)
	at com.helger.as2lib.supplementary.main.MainSendToMendelsonTestServer.main(MainSendToMendelsonTestServer.java:146)
Caused by: org.bouncycastle.cms.CMSException: unable to initialize cipher: Illegal key size
	at org.bouncycastle.cms.jcajce.JceCMSContentEncryptorBuilder$CMSOutputEncryptor.<init>(Unknown Source)
	at org.bouncycastle.cms.jcajce.JceCMSContentEncryptorBuilder.build(Unknown Source)
	at com.helger.as2lib.crypto.BCCryptoHelper.encrypt(BCCryptoHelper.java:479)
	at com.helger.as2lib.processor.sender.AS2SenderModule.secure(AS2SenderModule.java:421)
	at com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:841)
	... 2 more
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1060)
	at javax.crypto.Cipher.init(Cipher.java:1536)
	... 7 more
7530 [main] INFO com.helger.as2lib.supplementary.main.MainSendToMendelsonTestServer - 
OriginalMessageID: <github-phax-as2-lib-30082018180454+0300-4815@mycompanyAS2_mendelsontestAS2>
**Error message: org.bouncycastle.cms.CMSException: unable to initialize cipher: Illegal key size**
Sending duration: PT6.993524492S

7530 [main] INFO com.helger.as2lib.supplementary.main.MainSendToMendelsonTestServer - Done

You changed the encryption from 3DES to AES_256 ( in 4.1.1 it's working fine)
According to mendelson spec:
If you would like to test your AS2 server against the mendelson AS2 test server please use the following settings before sending messages:

MDN: sync
URL: http://testas2.mendelson-e-c.com:8080/as2/HttpReceiver
**Signature: Necessary, SHA-1
Encryption: Necessary, 3DES**
Sender AS2 id (your id): mycompanyAS2
Sender key (your key): (format pkcs#12, keystore pass "test"): Key1
Receiver AS2 id (test servers id): mendelsontestAS2
Receiver certificate (test servers certificate): (format PEM): Key2
Please contact us if you have trouble sending data to the AS2 test server.

You can change signature to sha-512 and encryption to aes_128
Thanks,
Itay

**Comment by phax** [comment]
This is a playground application for me :)
Changed back to 3DES for the next release
